---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/categories":
    get:
      summary: Retrieves all categories
      tags:
      - Categories
      responses:
        '200':
          description: categories found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
  "/api/categories/{id}":
    get:
      summary: Retrieves a category
      tags:
      - Categories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: category found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
  "/api/categories/1/sub_categories/1/drawers":
    get:
      summary: Retrieves all drawers
      tags:
      - Drawers
      responses:
        '200':
          description: drawers found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
  "/api/categories/1/sub_categories/1/drawers/{id}":
    get:
      summary: Retrieves a drawer
      tags:
      - Drawers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: drawer found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
  "/api/categories/1/sub_categories":
    post:
      summary: Creates a sub_category
      tags:
      - SubCategories
      security:
      - Bearer: {}
      parameters: []
      responses:
        '201':
          description: sub_category created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                category_id:
                  type: integer
              required:
              - name
              - category_id
    get:
      summary: Retrieves all sub_categories
      tags:
      - SubCategories
      responses:
        '200':
          description: sub_categories found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    category_id:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
  "/api/categories/1/sub_categories/1":
    put:
      summary: Updates a sub_category
      tags:
      - SubCategories
      security:
      - Bearer: {}
      parameters: []
      responses:
        '204':
          description: sub_category updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                category_id:
                  type: integer
              required:
              - name
              - category_id
    delete:
      summary: Deletes a sub_category
      tags:
      - SubCategories
      security:
      - Bearer: {}
      responses:
        '204':
          description: sub_category deleted
  "/api/categories/1/sub_categories/{id}":
    get:
      summary: Retrieves a sub_category
      tags:
      - SubCategories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: sub_category found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  category_id:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      name: Authorization
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization:
        Bearer {token}"'
